server:
  port: 9009

spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://config-server:9999"

  data:
    mongodb:
      uri: mongodb://admin:root@host.docker.internal:27017/notification-service?authSource=admin

  rabbitmq:
    host: host.docker.internal

client:
  email-client:
    base-url: https://api.brevo.com
    send-email-path: /v3/smtp/email

app:
  security:
    public-endpoints: [ ]

  email: huynhmin1007@gmail.com
  name: Minn Dev
  keys:
    brevo: <your_api_key>

  rabbitmq:
    exchanges:
      dlx: notification.domain.dlx
    queues:
      otp: notification.otp.queue
      notification: notification.events.queue
      dlq: notification.events.dlq