eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:discovery-server}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:unknown}

spring:
  data:
    redis:
      host: host.docker.internal
      port: 6379
      password:
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          time-between-eviction-runs: 1000ms

  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000ms
          max-attempts: 3
          multiplier: 2.0
          max-interval: 10000ms

grpc:
  client:
    identity-service:
      address: 'static://identity-service:9091'
      negotiation-type: plaintext
    profile-service:
      address: 'static://profile-service:9007'
      negotiation-type: plaintext
    search-service:
      address: 'static://search-service:9008'
      negotiation-type: plaintext
    inventory-service:
      address: 'static://inventory-service:9101'
      negotiation-type: plaintext

app:
  rabbitmq:
    exchanges:
      user: user.domain.exchange
      book: book.domain.exchange
      notification: notification.domain.exchange
      search: search.domain.exchange
    routing-keys:
      otp: notification.otp.*
      notification: notification.events.*
      dlq: dlq.key
      user: user.events.*
      book: book.events.*

management:
  tracing:
    sampling:
      probability: 1.0 # Bắt buộc phải có để 100% request đều có traceId