server:
  port: 9001

grpc:
  server:
    port: 9100

spring:
  application:
    name: bff-service
  config:
    import: "optional:configserver:http://config-server:9999"

app:
  security:
    public-endpoints: [ ]