server:
  port: 9008

spring:
  application:
    name: search-service
  config:
    import: "optional:configserver:http://config-server:9999"
  elasticsearch:
    uris: http://host.docker.internal:9200

  rabbitmq:
    host: host.docker.internal

app:
  security:
    public-endpoints: [ ]

  rabbitmq:
    exchange:
      dlx: search.domain.dlx
    queue:
      low-priority: search.priority.low.queue
      high-priority: search.priority.high.queue
      dlq: search.domain.dlq
    routing-key:
      dlq: search.dlq.key

    bindings:
      high-priority:
        - exchange: user.domain.exchange
          routing-key: user.core.*
        - exchange: book.domain.exchange
          routing-key: book.core.*
      low-priority:
        - exchange: book.domain.exchange
          routing-key: book.stats.*