server:
  port: 9007

spring:
  application:
    name: profile-service
  config:
    import: "optional:configserver:http://config-server:9999"

  neo4j:
    uri: bolt://host.docker.internal:7687
    authentication:
      username: neo4j
      password: 123456789

  rabbitmq:
    host: host.docker.internal

app:
  security:
    public-endpoints: [ ]

  rabbitmq:
    exchanges:
      dlx: profile.domain.dlx
    queues:
      low-priority: profile.low-priority.queue
      high-priority: profile.high-priority.queue